# Generated by Django 3.0.7 on 2020-06-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_key',
            name='apiKey',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
